- name: Add third party repositories
  tags:
    - apps
    - os_repo_apps
  block:
    - name: Add COPR
      become: true
      community.general.copr:
        name: "{{ item }}"
        state: enabled
      loop:
        - scottames/ghostty
        - atim/starship

- name: Install dnf packages
  tags:
    - apps
    - os_repo_apps
  block:
    - name: Ensure dnf is up to date
      ansible.builtin.dnf:
        update_cache: true
      become: true

    - name: Install dnf packages
      become: true
      ansible.builtin.package:
        name:
          - awscli
          - bat
          - btop
          - cargo
          - composer
          - difftastic
          - du-dust
          - duf
          - eza
          - fd-find
          - fzf
          - gimp
          - git
          - ghostty
          - golang
          - htop
          - jq
          - neovim
          - php-cli
          - php-common
          - php-mbstring
          - php-pdo
          - php-pecl-redis
          - php-sodium
          - php-xml
          - procs
          - ripgrep
          - rust
          - solaar
          - starship
          - stow
          - tldr
          - zoxide
        state: present

- name: Install Flatpak apps
  community.general.flatpak:
    name:
      - io.missioncenter.MissionCenter
      - com.bitwarden.desktop
      - com.github.IsmaelMartinez.teams_for_linux
      - com.logseq.Logseq
    state: present
  tags:
    - apps
    - flatpak_apps

- name: Include Docker tasks
  ansible.builtin.import_tasks: docker.yml
  tags:
    - apps
    - docker

- name: Include script-installed apps
  ansible.builtin.import_tasks: script_apps.yml
  tags:
    - apps
    - script_apps
