- name: Install Zed editor
  ansible.builtin.shell:
    cmd: curl -f https://zed.rs/install.sh | sh
    creates: "{{ ansible_env.HOME }}/.local/bin/zed"

- name: Install Bun
  ansible.builtin.shell:
    cmd: curl -fsSL https://bun.sh/install | sh
    creates: "{{ ansible_env.HOME }}/.bun/bin/bun"
